# Generated by Django 3.1 on 2020-08-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_navers'),
        ('navers', '0002_naver_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naver',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='navers', to='projects.Project'),
        ),
    ]
